### ISSUE TITLE
Question instruction needs correction

### ISSUE THREAD

**Issue by Jaylukmann** [heaganhenry/data-structures-algorithms#1]
The question instruction states that each word in a string should be reversed while  retaining the spaces. It should be each letter or character in a string should be reversed while retaining the spaces.

**Comment by heagandev** [comment]
Thanks for pointing that out. I think you're referring to "ReverseWords.py" right? The input is a string of words separated by spaces and the output should have the order preserved with each word reversed and spaces retained. I refactored the variable names to better reflect this.
